/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace AgentRegistry {
  export type AgentStruct = {
    name: string;
    endpoint: string;
    price: BigNumberish;
    category: string;
    reputation: BigNumberish;
    jobsCompleted: BigNumberish;
    jobsFailed: BigNumberish;
    totalEarned: BigNumberish;
    isActive: boolean;
    registeredAt: BigNumberish;
    exists: boolean;
  };

  export type AgentStructOutput = [
    name: string,
    endpoint: string,
    price: bigint,
    category: string,
    reputation: bigint,
    jobsCompleted: bigint,
    jobsFailed: bigint,
    totalEarned: bigint,
    isActive: boolean,
    registeredAt: bigint,
    exists: boolean
  ] & {
    name: string;
    endpoint: string;
    price: bigint;
    category: string;
    reputation: bigint;
    jobsCompleted: bigint;
    jobsFailed: bigint;
    totalEarned: bigint;
    isActive: boolean;
    registeredAt: bigint;
    exists: boolean;
  };

  export type EscrowRecordStruct = {
    amount: BigNumberish;
    requester: AddressLike;
    worker: AddressLike;
    deadline: BigNumberish;
    settled: boolean;
    exists: boolean;
  };

  export type EscrowRecordStructOutput = [
    amount: bigint,
    requester: string,
    worker: string,
    deadline: bigint,
    settled: boolean,
    exists: boolean
  ] & {
    amount: bigint;
    requester: string;
    worker: string;
    deadline: bigint;
    settled: boolean;
    exists: boolean;
  };

  export type JobStruct = {
    requester: AddressLike;
    worker: AddressLike;
    amount: BigNumberish;
    category: string;
    status: BytesLike;
    parentJobId: BigNumberish;
    createdAt: BigNumberish;
    completedAt: BigNumberish;
    exists: boolean;
  };

  export type JobStructOutput = [
    requester: string,
    worker: string,
    amount: bigint,
    category: string,
    status: string,
    parentJobId: bigint,
    createdAt: bigint,
    completedAt: bigint,
    exists: boolean
  ] & {
    requester: string;
    worker: string;
    amount: bigint;
    category: string;
    status: string;
    parentJobId: bigint;
    createdAt: bigint;
    completedAt: bigint;
    exists: boolean;
  };
}

export interface AgentRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "REPUTABLE_THRESHOLD"
      | "REPUTATION_FAILURE_PENALTY"
      | "REPUTATION_INITIAL"
      | "REPUTATION_MAX"
      | "REPUTATION_SUCCESS_BONUS"
      | "agents"
      | "categoryLeader"
      | "completeJob"
      | "contractOwner"
      | "createJob"
      | "disputeJob"
      | "escrowTimeoutBlocks"
      | "escrows"
      | "failJob"
      | "getAgent"
      | "getCategoryLeader"
      | "getDynamicPrice"
      | "getEfficiencyScore"
      | "getEscrow"
      | "getJob"
      | "getStats"
      | "govSetEscrowTimeout"
      | "govSetReputation"
      | "isReputable"
      | "jobs"
      | "nextJobId"
      | "refundEscrow"
      | "registerAgent"
      | "setActive"
      | "settlementToken"
      | "totalAgents"
      | "totalJobs"
      | "totalVolume"
      | "updateAgent"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentRegistered"
      | "AgentUpdated"
      | "EscrowRefunded"
      | "JobCompleted"
      | "JobCreated"
      | "JobDisputed"
      | "JobFailed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "REPUTABLE_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REPUTATION_FAILURE_PENALTY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REPUTATION_INITIAL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REPUTATION_MAX",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REPUTATION_SUCCESS_BONUS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "agents", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "categoryLeader",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "completeJob",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "contractOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createJob",
    values: [AddressLike, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeJob",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "escrowTimeoutBlocks",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "escrows",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "failJob",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCategoryLeader",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getDynamicPrice",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEfficiencyScore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEscrow",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getJob",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getStats", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "govSetEscrowTimeout",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "govSetReputation",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isReputable",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "jobs", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "nextJobId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "refundEscrow",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [string, string, BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "setActive", values: [boolean]): string;
  encodeFunctionData(
    functionFragment: "settlementToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalAgents",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "totalJobs", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalVolume",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateAgent",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "REPUTABLE_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REPUTATION_FAILURE_PENALTY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REPUTATION_INITIAL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REPUTATION_MAX",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REPUTATION_SUCCESS_BONUS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "agents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "categoryLeader",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeJob",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contractOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "disputeJob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "escrowTimeoutBlocks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "escrows", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "failJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCategoryLeader",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDynamicPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEfficiencyScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEscrow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getStats", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "govSetEscrowTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "govSetReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isReputable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "jobs", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nextJobId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "refundEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setActive", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "settlementToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalJobs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalVolume",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAgent",
    data: BytesLike
  ): Result;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [
    agent: AddressLike,
    name: string,
    category: string,
    price: BigNumberish
  ];
  export type OutputTuple = [
    agent: string,
    name: string,
    category: string,
    price: bigint
  ];
  export interface OutputObject {
    agent: string;
    name: string;
    category: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentUpdatedEvent {
  export type InputTuple = [
    agent: AddressLike,
    endpoint: string,
    price: BigNumberish
  ];
  export type OutputTuple = [agent: string, endpoint: string, price: bigint];
  export interface OutputObject {
    agent: string;
    endpoint: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowRefundedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    requester: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [jobId: bigint, requester: string, amount: bigint];
  export interface OutputObject {
    jobId: bigint;
    requester: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobCompletedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    worker: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [jobId: bigint, worker: string, amount: bigint];
  export interface OutputObject {
    jobId: bigint;
    worker: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobCreatedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    requester: AddressLike,
    worker: AddressLike,
    amount: BigNumberish,
    parentJobId: BigNumberish
  ];
  export type OutputTuple = [
    jobId: bigint,
    requester: string,
    worker: string,
    amount: bigint,
    parentJobId: bigint
  ];
  export interface OutputObject {
    jobId: bigint;
    requester: string;
    worker: string;
    amount: bigint;
    parentJobId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobDisputedEvent {
  export type InputTuple = [jobId: BigNumberish, requester: AddressLike];
  export type OutputTuple = [jobId: bigint, requester: string];
  export interface OutputObject {
    jobId: bigint;
    requester: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobFailedEvent {
  export type InputTuple = [jobId: BigNumberish, worker: AddressLike];
  export type OutputTuple = [jobId: bigint, worker: string];
  export interface OutputObject {
    jobId: bigint;
    worker: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AgentRegistry;
  waitForDeployment(): Promise<this>;

  interface: AgentRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  REPUTABLE_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  REPUTATION_FAILURE_PENALTY: TypedContractMethod<[], [bigint], "view">;

  REPUTATION_INITIAL: TypedContractMethod<[], [bigint], "view">;

  REPUTATION_MAX: TypedContractMethod<[], [bigint], "view">;

  REPUTATION_SUCCESS_BONUS: TypedContractMethod<[], [bigint], "view">;

  agents: TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        boolean
      ] & {
        name: string;
        endpoint: string;
        price: bigint;
        category: string;
        reputation: bigint;
        jobsCompleted: bigint;
        jobsFailed: bigint;
        totalEarned: bigint;
        isActive: boolean;
        registeredAt: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  categoryLeader: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  completeJob: TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;

  contractOwner: TypedContractMethod<[], [string], "view">;

  createJob: TypedContractMethod<
    [worker: AddressLike, category: string, parentJobId: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  disputeJob: TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;

  escrowTimeoutBlocks: TypedContractMethod<[], [bigint], "view">;

  escrows: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, boolean, boolean] & {
        amount: bigint;
        requester: string;
        worker: string;
        deadline: bigint;
        settled: boolean;
        exists: boolean;
      }
    ],
    "view"
  >;

  failJob: TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;

  getAgent: TypedContractMethod<
    [agent: AddressLike],
    [AgentRegistry.AgentStructOutput],
    "view"
  >;

  getCategoryLeader: TypedContractMethod<[category: string], [string], "view">;

  getDynamicPrice: TypedContractMethod<[agent: AddressLike], [bigint], "view">;

  getEfficiencyScore: TypedContractMethod<
    [agent: AddressLike],
    [bigint],
    "view"
  >;

  getEscrow: TypedContractMethod<
    [jobId: BigNumberish],
    [AgentRegistry.EscrowRecordStructOutput],
    "view"
  >;

  getJob: TypedContractMethod<
    [jobId: BigNumberish],
    [AgentRegistry.JobStructOutput],
    "view"
  >;

  getStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        _totalAgents: bigint;
        _totalJobs: bigint;
        _totalVolume: bigint;
        _nextJobId: bigint;
      }
    ],
    "view"
  >;

  govSetEscrowTimeout: TypedContractMethod<
    [blocksCount: BigNumberish],
    [void],
    "nonpayable"
  >;

  govSetReputation: TypedContractMethod<
    [agent: AddressLike, newScore: BigNumberish],
    [void],
    "nonpayable"
  >;

  isReputable: TypedContractMethod<[agent: AddressLike], [boolean], "view">;

  jobs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        requester: string;
        worker: string;
        amount: bigint;
        category: string;
        status: string;
        parentJobId: bigint;
        createdAt: bigint;
        completedAt: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  nextJobId: TypedContractMethod<[], [bigint], "view">;

  refundEscrow: TypedContractMethod<
    [jobId: BigNumberish],
    [void],
    "nonpayable"
  >;

  registerAgent: TypedContractMethod<
    [name: string, endpoint: string, price: BigNumberish, category: string],
    [void],
    "nonpayable"
  >;

  setActive: TypedContractMethod<[active: boolean], [void], "nonpayable">;

  settlementToken: TypedContractMethod<[], [string], "view">;

  totalAgents: TypedContractMethod<[], [bigint], "view">;

  totalJobs: TypedContractMethod<[], [bigint], "view">;

  totalVolume: TypedContractMethod<[], [bigint], "view">;

  updateAgent: TypedContractMethod<
    [endpoint: string, price: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "REPUTABLE_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REPUTATION_FAILURE_PENALTY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REPUTATION_INITIAL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REPUTATION_MAX"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REPUTATION_SUCCESS_BONUS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "agents"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        boolean
      ] & {
        name: string;
        endpoint: string;
        price: bigint;
        category: string;
        reputation: bigint;
        jobsCompleted: bigint;
        jobsFailed: bigint;
        totalEarned: bigint;
        isActive: boolean;
        registeredAt: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "categoryLeader"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "completeJob"
  ): TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "contractOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createJob"
  ): TypedContractMethod<
    [worker: AddressLike, category: string, parentJobId: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "disputeJob"
  ): TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "escrowTimeoutBlocks"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "escrows"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, boolean, boolean] & {
        amount: bigint;
        requester: string;
        worker: string;
        deadline: bigint;
        settled: boolean;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "failJob"
  ): TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAgent"
  ): TypedContractMethod<
    [agent: AddressLike],
    [AgentRegistry.AgentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCategoryLeader"
  ): TypedContractMethod<[category: string], [string], "view">;
  getFunction(
    nameOrSignature: "getDynamicPrice"
  ): TypedContractMethod<[agent: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEfficiencyScore"
  ): TypedContractMethod<[agent: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEscrow"
  ): TypedContractMethod<
    [jobId: BigNumberish],
    [AgentRegistry.EscrowRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getJob"
  ): TypedContractMethod<
    [jobId: BigNumberish],
    [AgentRegistry.JobStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        _totalAgents: bigint;
        _totalJobs: bigint;
        _totalVolume: bigint;
        _nextJobId: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "govSetEscrowTimeout"
  ): TypedContractMethod<[blocksCount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "govSetReputation"
  ): TypedContractMethod<
    [agent: AddressLike, newScore: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isReputable"
  ): TypedContractMethod<[agent: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "jobs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        requester: string;
        worker: string;
        amount: bigint;
        category: string;
        status: string;
        parentJobId: bigint;
        createdAt: bigint;
        completedAt: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextJobId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "refundEscrow"
  ): TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<
    [name: string, endpoint: string, price: BigNumberish, category: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setActive"
  ): TypedContractMethod<[active: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settlementToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalAgents"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalJobs"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalVolume"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "updateAgent"
  ): TypedContractMethod<
    [endpoint: string, price: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "AgentUpdated"
  ): TypedContractEvent<
    AgentUpdatedEvent.InputTuple,
    AgentUpdatedEvent.OutputTuple,
    AgentUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowRefunded"
  ): TypedContractEvent<
    EscrowRefundedEvent.InputTuple,
    EscrowRefundedEvent.OutputTuple,
    EscrowRefundedEvent.OutputObject
  >;
  getEvent(
    key: "JobCompleted"
  ): TypedContractEvent<
    JobCompletedEvent.InputTuple,
    JobCompletedEvent.OutputTuple,
    JobCompletedEvent.OutputObject
  >;
  getEvent(
    key: "JobCreated"
  ): TypedContractEvent<
    JobCreatedEvent.InputTuple,
    JobCreatedEvent.OutputTuple,
    JobCreatedEvent.OutputObject
  >;
  getEvent(
    key: "JobDisputed"
  ): TypedContractEvent<
    JobDisputedEvent.InputTuple,
    JobDisputedEvent.OutputTuple,
    JobDisputedEvent.OutputObject
  >;
  getEvent(
    key: "JobFailed"
  ): TypedContractEvent<
    JobFailedEvent.InputTuple,
    JobFailedEvent.OutputTuple,
    JobFailedEvent.OutputObject
  >;

  filters: {
    "AgentRegistered(address,string,string,uint256)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "AgentUpdated(address,string,uint256)": TypedContractEvent<
      AgentUpdatedEvent.InputTuple,
      AgentUpdatedEvent.OutputTuple,
      AgentUpdatedEvent.OutputObject
    >;
    AgentUpdated: TypedContractEvent<
      AgentUpdatedEvent.InputTuple,
      AgentUpdatedEvent.OutputTuple,
      AgentUpdatedEvent.OutputObject
    >;

    "EscrowRefunded(uint256,address,uint256)": TypedContractEvent<
      EscrowRefundedEvent.InputTuple,
      EscrowRefundedEvent.OutputTuple,
      EscrowRefundedEvent.OutputObject
    >;
    EscrowRefunded: TypedContractEvent<
      EscrowRefundedEvent.InputTuple,
      EscrowRefundedEvent.OutputTuple,
      EscrowRefundedEvent.OutputObject
    >;

    "JobCompleted(uint256,address,uint256)": TypedContractEvent<
      JobCompletedEvent.InputTuple,
      JobCompletedEvent.OutputTuple,
      JobCompletedEvent.OutputObject
    >;
    JobCompleted: TypedContractEvent<
      JobCompletedEvent.InputTuple,
      JobCompletedEvent.OutputTuple,
      JobCompletedEvent.OutputObject
    >;

    "JobCreated(uint256,address,address,uint256,uint256)": TypedContractEvent<
      JobCreatedEvent.InputTuple,
      JobCreatedEvent.OutputTuple,
      JobCreatedEvent.OutputObject
    >;
    JobCreated: TypedContractEvent<
      JobCreatedEvent.InputTuple,
      JobCreatedEvent.OutputTuple,
      JobCreatedEvent.OutputObject
    >;

    "JobDisputed(uint256,address)": TypedContractEvent<
      JobDisputedEvent.InputTuple,
      JobDisputedEvent.OutputTuple,
      JobDisputedEvent.OutputObject
    >;
    JobDisputed: TypedContractEvent<
      JobDisputedEvent.InputTuple,
      JobDisputedEvent.OutputTuple,
      JobDisputedEvent.OutputObject
    >;

    "JobFailed(uint256,address)": TypedContractEvent<
      JobFailedEvent.InputTuple,
      JobFailedEvent.OutputTuple,
      JobFailedEvent.OutputObject
    >;
    JobFailed: TypedContractEvent<
      JobFailedEvent.InputTuple,
      JobFailedEvent.OutputTuple,
      JobFailedEvent.OutputObject
    >;
  };
}
